#!/bin/bash
rm -rf ../dist/apache/css
rm -f ../dist/apache/*.html
mkdir ../dist/apache/css
echo "The ../dist/apache folder has been reset."

# Run html-minifier to compress HTML and JavaScript.
for VARIABLE in 400 401 403 404 405 406 407 408 409 410 411 412 413 414 415 416 417 418 421 422 423 424 426 428 429 431 451 500 501 502 503 504 505 506 507 508 510 511
do
    HTML_FILE_NAME="$VARIABLE.html"
    html-minifier --collapse-whitespace --remove-comments --remove-optional-tags --remove-redundant-attributes --remove-script-type-attributes --remove-tag-whitespace --use-short-doctype --minify-css true --minify-js true ../src/$HTML_FILE_NAME -o ../dist/apache/$HTML_FILE_NAME
    echo "$HTML_FILE_NAME minified"
done

# Run postcss to compress all the CSS files.
postcss ../src/css/ --dir ../dist/apache/css/
echo "All the CSS files have now been minified."

# JS_FILE_NAME="<your file name"
# uglifyjs --compress --mangle -o ../dist/apache/$JS_FILE_NAME -- $JS_FILE_NAME
# echo "$JS_FILE_NAME minified"

echo "Minification Complete!"
