#!/bin/bash
rm -Rf ../dist/nginx/*
mkdir ../dist/nginx/css
echo "The ../dist/nginx folder has been reset."

# Run html-minifier to compress HTML and JavaScript.
for VARIABLE in 444 494 495 496 497 499
do
    HTML_FILE_NAME="$VARIABLE.html"
    html-minifier --collapse-whitespace --remove-comments --remove-optional-tags --remove-redundant-attributes --remove-script-type-attributes --remove-tag-whitespace --use-short-doctype --minify-css true --minify-js true ../src/nginx/$HTML_FILE_NAME -o ../dist/nginx/$HTML_FILE_NAME
    echo "$HTML_FILE_NAME minified"
done

# Run postcss to compress all the CSS files.
postcss ../src/css/ --dir ../dist/nginx/css/
echo "All the CSS files have now been minified."

# Create Symbolic links to the static items that aren't compressed.
echo "Copying the /assets/ folder across..."
cp -R ../dist/apache/assets ../dist/nginx/
echo "Copying the /webfonts/ folder across..."
cp -R ../dist/apache/webfonts ../dist/nginx/

echo "Minification Complete!"
