#!/bin/bash
rm -rf ../dist/css
rm -f ../dist/*.html
mkdir ../dist/css
echo "The ../dist folder has been reset."

# Run html-minifier to compress HTML and JavaScript.
for VARIABLE in 400 401 403 404 405 406 407 408 411 413 414 415 429 431 500 501 502 503 504 505
do
    HTML_FILE_NAME="$VARIABLE.html"
    html-minifier --collapse-whitespace --remove-comments --remove-optional-tags --remove-redundant-attributes --remove-script-type-attributes --remove-tag-whitespace --use-short-doctype --minify-css true --minify-js true ../src/$HTML_FILE_NAME -o ../dist/$HTML_FILE_NAME
    echo "$HTML_FILE_NAME minified"
done

# Run postcss to compress all the CSS files.
postcss ../src/css/ --dir ../dist/css/
echo "All the CSS files have now been minified."

# JS_FILE_NAME="<your file name"
# uglifyjs --compress --mangle -o ../dist/$JS_FILE_NAME -- $JS_FILE_NAME
# echo "$JS_FILE_NAME minified"

echo "Minification Complete!"
